// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDapqaBm2EJknKCfdgLOhGoCxL8DqgAVUQ',
    appId: '1:446873974596:web:46b5f26692ad7e21c50911',
    messagingSenderId: '446873974596',
    projectId: 'login-f009e',
    authDomain: 'login-f009e.firebaseapp.com',
    storageBucket: 'login-f009e.appspot.com',
    measurementId: 'G-YSCG56M8JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKtfQbh6JWPy-9hOlF2Yw2ST1ZvQeqDw',
    appId: '1:446873974596:android:3a06b07baf8e51f4c50911',
    messagingSenderId: '446873974596',
    projectId: 'login-f009e',
    storageBucket: 'login-f009e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4KYvJC27NvPdX3swtCJ4D8XB-ubJKw_M',
    appId: '1:446873974596:ios:7b1909e44166b8d8c50911',
    messagingSenderId: '446873974596',
    projectId: 'login-f009e',
    storageBucket: 'login-f009e.appspot.com',
    iosClientId: '446873974596-g3rdl4g21tucun4ss63kv3ar96s7q1m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4KYvJC27NvPdX3swtCJ4D8XB-ubJKw_M',
    appId: '1:446873974596:ios:7b1909e44166b8d8c50911',
    messagingSenderId: '446873974596',
    projectId: 'login-f009e',
    storageBucket: 'login-f009e.appspot.com',
    iosClientId: '446873974596-g3rdl4g21tucun4ss63kv3ar96s7q1m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
